In [1]:
import numpy as np
import pandas as pd

In [2]:
police_killings = pd.read_csv('fatal-police-shootings-data.csv', encoding = "ISO-8859-1")
police_killings

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
5,11,Kenneth Joe Brown,2015-01-04,shot,gun,18.0,M,W,Guthrie,OK,False,attack,Not fleeing,False
6,13,Kenneth Arnold Buck,2015-01-05,shot,gun,22.0,M,H,Chandler,AZ,False,attack,Car,False
7,15,Brock Nichols,2015-01-06,shot,gun,35.0,M,W,Assaria,KS,False,attack,Not fleeing,False
8,16,Autumn Steele,2015-01-06,shot,unarmed,34.0,F,W,Burlington,IA,False,other,Not fleeing,True
9,17,Leslie Sapp III,2015-01-06,shot,toy weapon,47.0,M,B,Knoxville,PA,False,attack,Not fleeing,False
10,19,Patrick Wetter,2015-01-06,shot and Tasered,knife,25.0,M,W,Stockton,CA,False,attack,Not fleeing,False
11,21,Ron Sneed,2015-01-07,shot,gun,31.0,M,B,Freeport,TX,False,attack,Not fleeing,False
12,22,Hashim Hanif Ibn Abdul-Rasheed,2015-01-07,shot,knife,41.0,M,B,Columbus,OH,True,other,Not fleeing,False
13,25,Nicholas Ryan Brickman,2015-01-07,shot,gun,30.0,M,W,Des Moines,IA,False,attack,Car,False
14,27,Omarr Julian Maximillian Jackson,2015-01-07,shot,gun,37.0,M,B,New Orleans,LA,False,attack,Foot,True
15,29,Loren Simpson,2015-01-08,shot,NaN,28.0,M,W,Huntley,MT,False,undetermined,Not fleeing,False
16,32,James Dudley Barker,2015-01-08,shot,shovel,42.0,M,W,Salt Lake City,UT,False,attack,Not fleeing,True
17,36,Artago Damon Howard,2015-01-08,shot,unarmed,36.0,M,B,Strong,AR,False,attack,Not fleeing,False
18,37,Thomas Hamby,2015-01-08,shot,gun,49.0,M,W,Syracuse,UT,False,attack,Not fleeing,True
19,38,Jimmy Foreman,2015-01-09,shot,gun,71.0,M,W,England,AR,False,attack,Not fleeing,False
20,325,Andy Martinez,2015-01-09,shot,gun,33.0,M,H,El Paso,TX,False,attack,Not fleeing,False
21,42,Tommy Smith,2015-01-11,shot,gun,39.0,M,W,Arcola,IL,True,attack,Not fleeing,False
22,43,Brian Barbosa,2015-01-11,shot,gun,23.0,M,H,South Gate,CA,False,attack,Not fleeing,False
23,45,Salvador Figueroa,2015-01-11,shot and Tasered,gun,29.0,M,H,North Las Vegas,NV,False,attack,Foot,False
24,46,John Edward O'Keefe,2015-01-13,shot,gun,34.0,M,W,Albuquerque,NM,False,attack,Foot,True
25,48,Richard McClendon,2015-01-13,shot,knife,43.0,M,W,Jourdanton,TX,True,other,Not fleeing,False
26,49,Marcus Golden,2015-01-14,shot,NaN,24.0,M,B,St. Paul,MN,False,attack,Not fleeing,False
27,50,Michael Goebel,2015-01-14,shot,NaN,29.0,M,W,Franklin County,MO,False,attack,Not fleeing,False
28,51,Mario Jordan,2015-01-14,shot,gun,34.0,M,B,Chesapeake,VA,True,attack,Not fleeing,False
29,52,Talbot Schroeder,2015-01-14,shot,knife,75.0,M,W,Old Bridge,NJ,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4582,5038,Jeffrey Michael Gibble,2019-09-16,shot,gun,33.0,M,W,Elizabethon,TN,False,attack,Foot,False
4583,5041,Kristopher Adams,2019-09-16,shot,gun,37.0,M,NaN,Sanger,TX,False,attack,Foot,False
4584,5066,TK TK,2019-09-16,shot,gun,NaN,M,NaN,Houston,TX,False,attack,Foot,False
4585,5032,Gay Ellen Plack,2019-09-17,shot,hatchet,57.0,F,W,Richmond,VA,True,attack,Not fleeing,True
4586,5034,TK TK,2019-09-17,shot,vehicle,NaN,M,NaN,Milton,FL,False,attack,Car,False
4587,5043,Scott Gabriel Spangler,2019-09-18,shot,undetermined,43.0,M,NaN,Salem,OR,False,attack,Not fleeing,False
4588,5045,John Emory Sawyer,2019-09-19,shot,unknown weapon,74.0,M,NaN,Soddy Daisy,TN,True,other,Not fleeing,False
4589,5044,Jordan Michael Griffin,2019-09-20,shot,pellet gun,18.0,M,NaN,Long Beach,CA,False,attack,Not fleeing,False
4590,5058,Adam Paul English,2019-09-20,shot,gun,21.0,M,NaN,Gainesville,GA,False,attack,Not fleeing,True
4591,5049,Jeffrey Peterson,2019-09-21,shot,undetermined,29.0,M,NaN,Ada,OK,False,attack,Not fleeing,False
4592,5050,TK TK,2019-09-22,shot,gun,74.0,M,W,Austin,TX,False,attack,Not fleeing,False
4593,5046,TK TK,2019-09-23,shot,gun,NaN,M,H,Los Angeles,CA,False,other,NaN,False
4594,5047,Jeffery Tyler Aycock,2019-09-23,shot,gun,28.0,M,W,Floyd County,GA,False,attack,Foot,False
4595,5048,Charles Nation,2019-09-23,shot,unknown weapon,31.0,M,NaN,Lowell,AR,False,other,Not fleeing,False
4596,5051,Jarod Lee Smith,2019-09-24,shot,gun,41.0,M,NaN,Huntington,WV,False,attack,Not fleeing,False
4597,5068,Haywood Cannon,2019-09-24,shot,gun,67.0,M,NaN,Richlands,NC,False,attack,Car,False
4598,5069,Ronald Michael McCrary,2019-09-24,shot,knife,63.0,M,NaN,Sanford,NC,False,other,NaN,False
4599,5053,Daryl Strickland,2019-09-25,shot,gun,64.0,M,NaN,Hartsville,SC,False,attack,Not fleeing,False
4600,5067,Kevin Dudenhefer,2019-09-25,shot and Tasered,gun,32.0,M,W,Lacombe,LA,True,attack,Not fleeing,False
4601,5052,Leonard Shand,2019-09-26,shot,knife,49.0,M,B,Hyattsville,MD,False,attack,Not fleeing,False
4602,5054,Chad Willis Huggins,2019-09-26,shot,gun,28.0,M,W,Lexington County,SC,False,attack,Other,False
4603,5055,TK TK,2019-09-26,shot,vehicle,NaN,M,NaN,La Habra,CA,False,attack,Car,False
4604,5057,TK TK,2019-09-26,shot,gun,NaN,M,NaN,Dallas,TX,False,attack,Not fleeing,False
4605,5059,Haywood Cannon,2019-09-26,shot,gun,67.0,M,NaN,Jacksonville,NC,False,attack,Not fleeing,False
4606,5063,Jamaal Ramone Taylor,2019-09-28,shot,knife,31.0,M,NaN,Baltimore,MD,False,attack,Foot,False
4607,5065,TK TK,2019-09-28,shot,gun,NaN,M,NaN,Boston,MA,False,attack,Foot,False
4608,5060,Dewayne Morgan,2019-09-29,shot and Tasered,NaN,37.0,M,W,Longview,TX,False,attack,Foot,False
4609,5061,TK TK,2019-09-29,shot,undetermined,NaN,M,NaN,Monument,CO,False,attack,Not fleeing,False
4610,5062,Richard Cabrera,2019-09-29,shot,gun,38.0,M,NaN,Miami,FL,False,attack,NaN,False
4611,5064,Antonio Williams,2019-09-29,shot,gun,27.0,M,NaN,New York,NY,False,attack,Not fleeing,False

In [3]:
household_income = pd.read_csv('MedianHouseholdIncome2015.csv', encoding = "ISO-8859-1")
household_income

      Geographic Area                    City Median Income
0                  AL              Abanda CDP         11207
1                  AL          Abbeville city         25615
2                  AL         Adamsville city         42575
3                  AL            Addison town         37083
4                  AL              Akron town         21667
5                  AL          Alabaster city         71816
6                  AL        Albertville city         32911
7                  AL     Alexander City city         29874
8                  AL          Alexandria CDP         56058
9                  AL         Aliceville city         21131
10                 AL            Allgood town         42009
11                 AL            Altoona town         27566
12                 AL          Andalusia city         31968
13                 AL           Anderson town         34792
14                 AL           Anniston city         29681
15                 AL               Arab city         40292
16                 AL            Ardmore town         35670
17                 AL               Argo town         57212
18                 AL             Ariton town         24286
19                 AL              Arley town         28750
20                 AL            Ashford town         42704
21                 AL            Ashland town         31438
22                 AL           Ashville city         40547
23                 AL             Athens city         47542
24                 AL             Atmore city         26775
25                 AL            Attalla city         37191
26                 AL             Auburn city         38342
27                 AL       Autaugaville town         24833
28                 AL               Avon town         40417
29                 AL                Axis CDP         55750
...               ...                     ...           ...
29292              WY          South Park CDP         97286
29293              WY  Star Valley Ranch town         70326
29294              WY               Story CDP         45561
29295              WY           Sundance town         56452
29296              WY           Superior town         55000
29297              WY          Table Rock CDP           NaN
29298              WY              Taylor CDP         77917
29299              WY          Ten Sleep town         51250
29300              WY       Teton Village CDP           NaN
29301              WY             Thayne town         41250
29302              WY        Thermopolis town         43438
29303              WY         Torrington city         40911
29304              WY         Turnerville CDP         40795
29305              WY              Upton town         61333
29306              WY                Urie CDP         89044
29307              WY        Van Tassell town           NaN
29308              WY             Veteran CDP           NaN
29309              WY          Vista West CDP        101667
29310              WY          Wamsutter town         80179
29311              WY          Warren AFB CDP         50982
29312              WY              Washam CDP           NaN
29313              WY     Westview Circle CDP           NaN
29314              WY          Wheatland town         34984
29315              WY             Whiting CDP           NaN
29316              WY              Wilson CDP         94792
29317              WY  Woods Landing-Jelm CDP           NaN
29318              WY            Worland city         41523
29319              WY             Wright town         77114
29320              WY              Yoder town         37500
29321              WY           Y-O Ranch CDP           NaN

[29322 rows x 3 columns]

In [4]:
poverty_rate = pd.read_csv('PercentagePeopleBelowPovertyLevel.csv', encoding = "ISO-8859-1")
poverty_rate

      Geographic Area                    City poverty_rate
0                  AL              Abanda CDP         78.8
1                  AL          Abbeville city         29.1
2                  AL         Adamsville city         25.5
3                  AL            Addison town         30.7
4                  AL              Akron town           42
5                  AL          Alabaster city         11.2
6                  AL        Albertville city         26.7
7                  AL     Alexander City city         30.4
8                  AL          Alexandria CDP          9.7
9                  AL         Aliceville city         41.3
10                 AL            Allgood town         27.7
11                 AL            Altoona town         27.5
12                 AL          Andalusia city         24.5
13                 AL           Anderson town         13.8
14                 AL           Anniston city         31.7
15                 AL               Arab city         16.7
16                 AL            Ardmore town         19.1
17                 AL               Argo town          8.6
18                 AL             Ariton town         37.6
19                 AL              Arley town         31.6
20                 AL            Ashford town         18.8
21                 AL            Ashland town         22.4
22                 AL           Ashville city         28.3
23                 AL             Athens city           13
24                 AL             Atmore city         24.7
25                 AL            Attalla city         20.3
26                 AL             Auburn city         31.8
27                 AL       Autaugaville town         24.1
28                 AL               Avon town         22.2
29                 AL                Axis CDP          6.8
...               ...                     ...          ...
29299              WY          South Park CDP            0
29300              WY  Star Valley Ranch town          4.8
29301              WY               Story CDP          9.4
29302              WY           Sundance town          4.7
29303              WY           Superior town         14.3
29304              WY          Table Rock CDP            -
29305              WY              Taylor CDP            0
29306              WY          Ten Sleep town         14.8
29307              WY       Teton Village CDP            0
29308              WY             Thayne town         14.1
29309              WY        Thermopolis town         13.4
29310              WY         Torrington city         20.9
29311              WY         Turnerville CDP            0
29312              WY              Upton town         15.5
29313              WY                Urie CDP          2.2
29314              WY        Van Tassell town         42.9
29315              WY             Veteran CDP            0
29316              WY          Vista West CDP          3.3
29317              WY          Wamsutter town          6.4
29318              WY          Warren AFB CDP          2.2
29319              WY              Washam CDP            0
29320              WY     Westview Circle CDP          100
29321              WY          Wheatland town           12
29322              WY             Whiting CDP            0
29323              WY              Wilson CDP          2.9
29324              WY  Woods Landing-Jelm CDP         18.6
29325              WY            Worland city         15.3
29326              WY             Wright town          5.9
29327              WY              Yoder town          5.4
29328              WY           Y-O Ranch CDP            0

[29329 rows x 3 columns]

In [5]:
high_school_completion = pd.read_csv('PercentOver25CompletedHighSchool.csv', encoding = "ISO-8859-1")
high_school_completion

      Geographic Area                    City percent_completed_hs
0                  AL              Abanda CDP                 21.2
1                  AL          Abbeville city                 69.1
2                  AL         Adamsville city                 78.9
3                  AL            Addison town                 81.4
4                  AL              Akron town                 68.6
5                  AL          Alabaster city                 89.3
6                  AL        Albertville city                 72.7
7                  AL     Alexander City city                 78.1
8                  AL          Alexandria CDP                 88.8
9                  AL         Aliceville city                 74.3
10                 AL            Allgood town                 48.1
11                 AL            Altoona town                 66.9
12                 AL          Andalusia city                 81.1
13                 AL           Anderson town                 85.7
14                 AL           Anniston city                 79.8
15                 AL               Arab city                 87.6
16                 AL            Ardmore town                 77.7
17                 AL               Argo town                 87.5
18                 AL             Ariton town                 71.3
19                 AL              Arley town                 80.6
20                 AL            Ashford town                 83.5
21                 AL            Ashland town                 77.9
22                 AL           Ashville city                 77.6
23                 AL             Athens city                 83.4
24                 AL             Atmore city                 73.7
25                 AL            Attalla city                   76
26                 AL             Auburn city                 94.3
27                 AL       Autaugaville town                 71.2
28                 AL               Avon town                 82.8
29                 AL                Axis CDP                 79.9
...               ...                     ...                  ...
29299              WY          South Park CDP                   99
29300              WY  Star Valley Ranch town                 88.5
29301              WY               Story CDP                 93.9
29302              WY           Sundance town                 93.1
29303              WY           Superior town                 91.6
29304              WY          Table Rock CDP                    -
29305              WY              Taylor CDP                  100
29306              WY          Ten Sleep town                 84.4
29307              WY       Teton Village CDP                  100
29308              WY             Thayne town                 86.5
29309              WY        Thermopolis town                 92.5
29310              WY         Torrington city                 90.6
29311              WY         Turnerville CDP                  100
29312              WY              Upton town                 92.5
29313              WY                Urie CDP                   98
29314              WY        Van Tassell town                  100
29315              WY             Veteran CDP                   50
29316              WY          Vista West CDP                 93.1
29317              WY          Wamsutter town                 93.3
29318              WY          Warren AFB CDP                 96.6
29319              WY              Washam CDP                  100
29320              WY     Westview Circle CDP                  100
29321              WY          Wheatland town                 92.7
29322              WY             Whiting CDP                  100
29323              WY              Wilson CDP                  100
29324              WY  Woods Landing-Jelm CDP                  100
29325              WY            Worland city                 85.6
29326              WY             Wright town                 89.2
29327              WY              Yoder town                 79.4
29328              WY           Y-O Ranch CDP                  100

[29329 rows x 3 columns]

In [6]:
race_by_city = pd.read_csv('ShareRaceByCity.csv', encoding = "ISO-8859-1")
race_by_city

,Geographic area,City,share_white,share_black,share_native_american,share_asian,share_hispanic
0,AL,Abanda CDP,67.2,30.2,0,0,1.6
1,AL,Abbeville city,54.4,41.4,0.1,1,3.1
2,AL,Adamsville city,52.3,44.9,0.5,0.3,2.3
3,AL,Addison town,99.1,0.1,0,0.1,0.4
4,AL,Akron town,13.2,86.5,0,0,0.3
5,AL,Alabaster city,79.4,13.5,0.4,0.9,9
6,AL,Albertville city,75.9,1.9,0.8,0.5,27.9
7,AL,Alexander City city,62.2,32,0.2,0.9,4.8
8,AL,Alexandria CDP,87.4,10.2,0.3,0.5,0.9
9,AL,Aliceville city,22.6,74.9,0.1,0,1.2
10,AL,Allgood town,79.6,0.6,0.3,0.6,49.4
11,AL,Altoona town,95.8,1.7,0.2,0.2,1.1
12,AL,Andalusia city,70.5,25.9,0.4,1,1.9
13,AL,Anderson town,97.9,0,0.4,0,0.7
14,AL,Anniston city,44.7,51.5,0.3,0.8,2.7
15,AL,Arab city,96.6,0.1,0.6,0.7,1.7
16,AL,Ardmore town,94.3,1.9,0.8,0.9,1.3
17,AL,Argo town,94.1,3.6,0.4,0.3,0.5
18,AL,Ariton town,78.3,19.2,0,0.1,6
19,AL,Arley town,94.4,0,0.6,0.3,1.4
20,AL,Ashford town,79,19.5,0.2,0.2,0.8
21,AL,Ashland town,71.5,24.1,0.3,0.7,5.7
22,AL,Ashville city,75.8,20.3,0.2,0.3,3.8
23,AL,Athens city,73,17.5,0.6,0.9,8.8
24,AL,Atmore city,40,55.6,1.8,0.3,1.8
25,AL,Attalla city,81.5,12.7,0.4,0.5,4.7
26,AL,Auburn city,75.1,16.5,0.3,5.3,2.9
27,AL,Autaugaville town,31.3,66.8,0.2,0,0.8
28,AL,Avon town,94.7,1.8,1.8,0,1.3
29,AL,Axis CDP,66.8,26.9,3.2,0.1,0.9
...,...,...,...,...,...,...,...
29238,WY,South Park CDP,94,0.1,0.2,0.5,5.9
29239,WY,Star Valley Ranch town,96.3,0.1,0.8,0.6,3.4
29240,WY,Story CDP,97.9,0,0.7,0.2,1.7
29241,WY,Sundance town,97.8,0.2,0.8,0,1.2
29242,WY,Superior town,91.4,0.6,1.8,0.6,12.8
29243,WY,Table Rock CDP,(X),(X),(X),(X),(X)
29244,WY,Taylor CDP,87.8,0,1.1,0,13.3
29245,WY,Ten Sleep town,97.3,0,0.8,0.4,0.8
29246,WY,Teton Village CDP,93.9,0.6,0.3,1.2,3.9
29247,WY,Thayne town,91.5,0,0,1.1,9.3
29248,WY,Thermopolis town,96.4,0.3,0.9,0.5,2.2
29249,WY,Torrington city,93.2,1,0.9,0.5,11.3
29250,WY,Turnerville CDP,99,0,0.5,0,0.5
29251,WY,Upton town,95.6,0.2,1.7,0.5,2.3
29252,WY,Urie CDP,99.6,0,0,0,1.1
29253,WY,Van Tassell town,100,0,0,0,0
29254,WY,Veteran CDP,87,0,8.7,0,0
29255,WY,Vista West CDP,97.1,0,0.3,0.1,1.9
29256,WY,Wamsutter town,82.7,0.7,2.9,0,19.7
29257,WY,Warren AFB CDP,79.1,7.6,0.7,2.3,11.3
29258,WY,Washam CDP,100,0,0,0,3.9
29259,WY,Westview Circle CDP,100,0,0,0,1.9
29260,WY,Wheatland town,95.1,0.1,0.4,0.7,7.4
29261,WY,Whiting CDP,96.4,0,0,0,6
29262,WY,Wilson CDP,97.5,0.2,0.3,0.8,1.8
29263,WY,Woods Landing-Jelm CDP,95.9,0,0,2.1,0
29264,WY,Worland city,89.9,0.3,1.3,0.6,16.6
29265,WY,Wright town,94.5,0.1,1.4,0.2,6.2
29266,WY,Yoder town,97.4,0,0,0,4
29267,WY,Y-O Ranch CDP,92.8,1.5,2.6,0,11.8

In [7]:
police = pd.read_csv('fatal-police-shootings-data.csv')

In [8]:
import numpy as np
import pandas as pd

In [9]:
police = pd.read_csv('fatal-police-shootings-data.csv')

In [10]:
police

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
5,11,Kenneth Joe Brown,2015-01-04,shot,gun,18.0,M,W,Guthrie,OK,False,attack,Not fleeing,False
6,13,Kenneth Arnold Buck,2015-01-05,shot,gun,22.0,M,H,Chandler,AZ,False,attack,Car,False
7,15,Brock Nichols,2015-01-06,shot,gun,35.0,M,W,Assaria,KS,False,attack,Not fleeing,False
8,16,Autumn Steele,2015-01-06,shot,unarmed,34.0,F,W,Burlington,IA,False,other,Not fleeing,True
9,17,Leslie Sapp III,2015-01-06,shot,toy weapon,47.0,M,B,Knoxville,PA,False,attack,Not fleeing,False
10,19,Patrick Wetter,2015-01-06,shot and Tasered,knife,25.0,M,W,Stockton,CA,False,attack,Not fleeing,False
11,21,Ron Sneed,2015-01-07,shot,gun,31.0,M,B,Freeport,TX,False,attack,Not fleeing,False
12,22,Hashim Hanif Ibn Abdul-Rasheed,2015-01-07,shot,knife,41.0,M,B,Columbus,OH,True,other,Not fleeing,False
13,25,Nicholas Ryan Brickman,2015-01-07,shot,gun,30.0,M,W,Des Moines,IA,False,attack,Car,False
14,27,Omarr Julian Maximillian Jackson,2015-01-07,shot,gun,37.0,M,B,New Orleans,LA,False,attack,Foot,True
15,29,Loren Simpson,2015-01-08,shot,NaN,28.0,M,W,Huntley,MT,False,undetermined,Not fleeing,False
16,32,James Dudley Barker,2015-01-08,shot,shovel,42.0,M,W,Salt Lake City,UT,False,attack,Not fleeing,True
17,36,Artago Damon Howard,2015-01-08,shot,unarmed,36.0,M,B,Strong,AR,False,attack,Not fleeing,False
18,37,Thomas Hamby,2015-01-08,shot,gun,49.0,M,W,Syracuse,UT,False,attack,Not fleeing,True
19,38,Jimmy Foreman,2015-01-09,shot,gun,71.0,M,W,England,AR,False,attack,Not fleeing,False
20,325,Andy Martinez,2015-01-09,shot,gun,33.0,M,H,El Paso,TX,False,attack,Not fleeing,False
21,42,Tommy Smith,2015-01-11,shot,gun,39.0,M,W,Arcola,IL,True,attack,Not fleeing,False
22,43,Brian Barbosa,2015-01-11,shot,gun,23.0,M,H,South Gate,CA,False,attack,Not fleeing,False
23,45,Salvador Figueroa,2015-01-11,shot and Tasered,gun,29.0,M,H,North Las Vegas,NV,False,attack,Foot,False
24,46,John Edward O'Keefe,2015-01-13,shot,gun,34.0,M,W,Albuquerque,NM,False,attack,Foot,True
25,48,Richard McClendon,2015-01-13,shot,knife,43.0,M,W,Jourdanton,TX,True,other,Not fleeing,False
26,49,Marcus Golden,2015-01-14,shot,NaN,24.0,M,B,St. Paul,MN,False,attack,Not fleeing,False
27,50,Michael Goebel,2015-01-14,shot,NaN,29.0,M,W,Franklin County,MO,False,attack,Not fleeing,False
28,51,Mario Jordan,2015-01-14,shot,gun,34.0,M,B,Chesapeake,VA,True,attack,Not fleeing,False
29,52,Talbot Schroeder,2015-01-14,shot,knife,75.0,M,W,Old Bridge,NJ,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4582,5038,Jeffrey Michael Gibble,2019-09-16,shot,gun,33.0,M,W,Elizabethon,TN,False,attack,Foot,False
4583,5041,Kristopher Adams,2019-09-16,shot,gun,37.0,M,NaN,Sanger,TX,False,attack,Foot,False
4584,5066,TK TK,2019-09-16,shot,gun,NaN,M,NaN,Houston,TX,False,attack,Foot,False
4585,5032,Gay Ellen Plack,2019-09-17,shot,hatchet,57.0,F,W,Richmond,VA,True,attack,Not fleeing,True
4586,5034,TK TK,2019-09-17,shot,vehicle,NaN,M,NaN,Milton,FL,False,attack,Car,False
4587,5043,Scott Gabriel Spangler,2019-09-18,shot,undetermined,43.0,M,NaN,Salem,OR,False,attack,Not fleeing,False
4588,5045,John Emory Sawyer,2019-09-19,shot,unknown weapon,74.0,M,NaN,Soddy Daisy,TN,True,other,Not fleeing,False
4589,5044,Jordan Michael Griffin,2019-09-20,shot,pellet gun,18.0,M,NaN,Long Beach,CA,False,attack,Not fleeing,False
4590,5058,Adam Paul English,2019-09-20,shot,gun,21.0,M,NaN,Gainesville,GA,False,attack,Not fleeing,True
4591,5049,Jeffrey Peterson,2019-09-21,shot,undetermined,29.0,M,NaN,Ada,OK,False,attack,Not fleeing,False
4592,5050,TK TK,2019-09-22,shot,gun,74.0,M,W,Austin,TX,False,attack,Not fleeing,False
4593,5046,TK TK,2019-09-23,shot,gun,NaN,M,H,Los Angeles,CA,False,other,NaN,False
4594,5047,Jeffery Tyler Aycock,2019-09-23,shot,gun,28.0,M,W,Floyd County,GA,False,attack,Foot,False
4595,5048,Charles Nation,2019-09-23,shot,unknown weapon,31.0,M,NaN,Lowell,AR,False,other,Not fleeing,False
4596,5051,Jarod Lee Smith,2019-09-24,shot,gun,41.0,M,NaN,Huntington,WV,False,attack,Not fleeing,False
4597,5068,Haywood Cannon,2019-09-24,shot,gun,67.0,M,NaN,Richlands,NC,False,attack,Car,False
4598,5069,Ronald Michael McCrary,2019-09-24,shot,knife,63.0,M,NaN,Sanford,NC,False,other,NaN,False
4599,5053,Daryl Strickland,2019-09-25,shot,gun,64.0,M,NaN,Hartsville,SC,False,attack,Not fleeing,False
4600,5067,Kevin Dudenhefer,2019-09-25,shot and Tasered,gun,32.0,M,W,Lacombe,LA,True,attack,Not fleeing,False
4601,5052,Leonard Shand,2019-09-26,shot,knife,49.0,M,B,Hyattsville,MD,False,attack,Not fleeing,False
4602,5054,Chad Willis Huggins,2019-09-26,shot,gun,28.0,M,W,Lexington County,SC,False,attack,Other,False
4603,5055,TK TK,2019-09-26,shot,vehicle,NaN,M,NaN,La Habra,CA,False,attack,Car,False
4604,5057,TK TK,2019-09-26,shot,gun,NaN,M,NaN,Dallas,TX,False,attack,Not fleeing,False
4605,5059,Haywood Cannon,2019-09-26,shot,gun,67.0,M,NaN,Jacksonville,NC,False,attack,Not fleeing,False
4606,5063,Jamaal Ramone Taylor,2019-09-28,shot,knife,31.0,M,NaN,Baltimore,MD,False,attack,Foot,False
4607,5065,TK TK,2019-09-28,shot,gun,NaN,M,NaN,Boston,MA,False,attack,Foot,False
4608,5060,Dewayne Morgan,2019-09-29,shot and Tasered,NaN,37.0,M,W,Longview,TX,False,attack,Foot,False
4609,5061,TK TK,2019-09-29,shot,undetermined,NaN,M,NaN,Monument,CO,False,attack,Not fleeing,False
4610,5062,Richard Cabrera,2019-09-29,shot,gun,38.0,M,NaN,Miami,FL,False,attack,NaN,False
4611,5064,Antonio Williams,2019-09-29,shot,gun,27.0,M,NaN,New York,NY,False,attack,Not fleeing,False

In [11]:
police = pd.read_csv('fatal-police-shootings-data.csv')
police['city'] = police['city'].str.replace(r' city', '') #removes anything with a lower-cased ' city', done to try to clean up data
police['city'] = police['city'].str.lower() #makes everything lower case, done to try to clean up data

In [12]:
police

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,san francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,evans,CO,False,attack,Not fleeing,False
5,11,Kenneth Joe Brown,2015-01-04,shot,gun,18.0,M,W,guthrie,OK,False,attack,Not fleeing,False
6,13,Kenneth Arnold Buck,2015-01-05,shot,gun,22.0,M,H,chandler,AZ,False,attack,Car,False
7,15,Brock Nichols,2015-01-06,shot,gun,35.0,M,W,assaria,KS,False,attack,Not fleeing,False
8,16,Autumn Steele,2015-01-06,shot,unarmed,34.0,F,W,burlington,IA,False,other,Not fleeing,True
9,17,Leslie Sapp III,2015-01-06,shot,toy weapon,47.0,M,B,knoxville,PA,False,attack,Not fleeing,False
10,19,Patrick Wetter,2015-01-06,shot and Tasered,knife,25.0,M,W,stockton,CA,False,attack,Not fleeing,False
11,21,Ron Sneed,2015-01-07,shot,gun,31.0,M,B,freeport,TX,False,attack,Not fleeing,False
12,22,Hashim Hanif Ibn Abdul-Rasheed,2015-01-07,shot,knife,41.0,M,B,columbus,OH,True,other,Not fleeing,False
13,25,Nicholas Ryan Brickman,2015-01-07,shot,gun,30.0,M,W,des moines,IA,False,attack,Car,False
14,27,Omarr Julian Maximillian Jackson,2015-01-07,shot,gun,37.0,M,B,new orleans,LA,False,attack,Foot,True
15,29,Loren Simpson,2015-01-08,shot,NaN,28.0,M,W,huntley,MT,False,undetermined,Not fleeing,False
16,32,James Dudley Barker,2015-01-08,shot,shovel,42.0,M,W,salt lake city,UT,False,attack,Not fleeing,True
17,36,Artago Damon Howard,2015-01-08,shot,unarmed,36.0,M,B,strong,AR,False,attack,Not fleeing,False
18,37,Thomas Hamby,2015-01-08,shot,gun,49.0,M,W,syracuse,UT,False,attack,Not fleeing,True
19,38,Jimmy Foreman,2015-01-09,shot,gun,71.0,M,W,england,AR,False,attack,Not fleeing,False
20,325,Andy Martinez,2015-01-09,shot,gun,33.0,M,H,el paso,TX,False,attack,Not fleeing,False
21,42,Tommy Smith,2015-01-11,shot,gun,39.0,M,W,arcola,IL,True,attack,Not fleeing,False
22,43,Brian Barbosa,2015-01-11,shot,gun,23.0,M,H,south gate,CA,False,attack,Not fleeing,False
23,45,Salvador Figueroa,2015-01-11,shot and Tasered,gun,29.0,M,H,north las vegas,NV,False,attack,Foot,False
24,46,John Edward O'Keefe,2015-01-13,shot,gun,34.0,M,W,albuquerque,NM,False,attack,Foot,True
25,48,Richard McClendon,2015-01-13,shot,knife,43.0,M,W,jourdanton,TX,True,other,Not fleeing,False
26,49,Marcus Golden,2015-01-14,shot,NaN,24.0,M,B,st. paul,MN,False,attack,Not fleeing,False
27,50,Michael Goebel,2015-01-14,shot,NaN,29.0,M,W,franklin county,MO,False,attack,Not fleeing,False
28,51,Mario Jordan,2015-01-14,shot,gun,34.0,M,B,chesapeake,VA,True,attack,Not fleeing,False
29,52,Talbot Schroeder,2015-01-14,shot,knife,75.0,M,W,old bridge,NJ,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4582,5038,Jeffrey Michael Gibble,2019-09-16,shot,gun,33.0,M,W,elizabethon,TN,False,attack,Foot,False
4583,5041,Kristopher Adams,2019-09-16,shot,gun,37.0,M,NaN,sanger,TX,False,attack,Foot,False
4584,5066,TK TK,2019-09-16,shot,gun,NaN,M,NaN,houston,TX,False,attack,Foot,False
4585,5032,Gay Ellen Plack,2019-09-17,shot,hatchet,57.0,F,W,richmond,VA,True,attack,Not fleeing,True
4586,5034,TK TK,2019-09-17,shot,vehicle,NaN,M,NaN,milton,FL,False,attack,Car,False
4587,5043,Scott Gabriel Spangler,2019-09-18,shot,undetermined,43.0,M,NaN,salem,OR,False,attack,Not fleeing,False
4588,5045,John Emory Sawyer,2019-09-19,shot,unknown weapon,74.0,M,NaN,soddy daisy,TN,True,other,Not fleeing,False
4589,5044,Jordan Michael Griffin,2019-09-20,shot,pellet gun,18.0,M,NaN,long beach,CA,False,attack,Not fleeing,False
4590,5058,Adam Paul English,2019-09-20,shot,gun,21.0,M,NaN,gainesville,GA,False,attack,Not fleeing,True
4591,5049,Jeffrey Peterson,2019-09-21,shot,undetermined,29.0,M,NaN,ada,OK,False,attack,Not fleeing,False
4592,5050,TK TK,2019-09-22,shot,gun,74.0,M,W,austin,TX,False,attack,Not fleeing,False
4593,5046,TK TK,2019-09-23,shot,gun,NaN,M,H,los angeles,CA,False,other,NaN,False
4594,5047,Jeffery Tyler Aycock,2019-09-23,shot,gun,28.0,M,W,floyd county,GA,False,attack,Foot,False
4595,5048,Charles Nation,2019-09-23,shot,unknown weapon,31.0,M,NaN,lowell,AR,False,other,Not fleeing,False
4596,5051,Jarod Lee Smith,2019-09-24,shot,gun,41.0,M,NaN,huntington,WV,False,attack,Not fleeing,False
4597,5068,Haywood Cannon,2019-09-24,shot,gun,67.0,M,NaN,richlands,NC,False,attack,Car,False
4598,5069,Ronald Michael McCrary,2019-09-24,shot,knife,63.0,M,NaN,sanford,NC,False,other,NaN,False
4599,5053,Daryl Strickland,2019-09-25,shot,gun,64.0,M,NaN,hartsville,SC,False,attack,Not fleeing,False
4600,5067,Kevin Dudenhefer,2019-09-25,shot and Tasered,gun,32.0,M,W,lacombe,LA,True,attack,Not fleeing,False
4601,5052,Leonard Shand,2019-09-26,shot,knife,49.0,M,B,hyattsville,MD,False,attack,Not fleeing,False
4602,5054,Chad Willis Huggins,2019-09-26,shot,gun,28.0,M,W,lexington county,SC,False,attack,Other,False
4603,5055,TK TK,2019-09-26,shot,vehicle,NaN,M,NaN,la habra,CA,False,attack,Car,False
4604,5057,TK TK,2019-09-26,shot,gun,NaN,M,NaN,dallas,TX,False,attack,Not fleeing,False
4605,5059,Haywood Cannon,2019-09-26,shot,gun,67.0,M,NaN,jacksonville,NC,False,attack,Not fleeing,False
4606,5063,Jamaal Ramone Taylor,2019-09-28,shot,knife,31.0,M,NaN,baltimore,MD,False,attack,Foot,False
4607,5065,TK TK,2019-09-28,shot,gun,NaN,M,NaN,boston,MA,False,attack,Foot,False
4608,5060,Dewayne Morgan,2019-09-29,shot and Tasered,NaN,37.0,M,W,longview,TX,False,attack,Foot,False
4609,5061,TK TK,2019-09-29,shot,undetermined,NaN,M,NaN,monument,CO,False,attack,Not fleeing,False
4610,5062,Richard Cabrera,2019-09-29,shot,gun,38.0,M,NaN,miami,FL,False,attack,NaN,False
4611,5064,Antonio Williams,2019-09-29,shot,gun,27.0,M,NaN,new york,NY,False,attack,Not fleeing,False

In [13]:
police.shape

(4612, 14)

In [14]:
police.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,san francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,evans,CO,False,attack,Not fleeing,False

In [15]:
police["id"]

0          3
1          4
2          5
3          8
4          9
5         11
6         13
7         15
8         16
9         17
10        19
11        21
12        22
13        25
14        27
15        29
16        32
17        36
18        37
19        38
20       325
21        42
22        43
23        45
24        46
25        48
26        49
27        50
28        51
29        52
        ...
4582    5038
4583    5041
4584    5066
4585    5032
4586    5034
4587    5043
4588    5045
4589    5044
4590    5058
4591    5049
4592    5050
4593    5046
4594    5047
4595    5048
4596    5051
4597    5068
4598    5069
4599    5053
4600    5067
4601    5052
4602    5054
4603    5055
4604    5057
4605    5059
4606    5063
4607    5065
4608    5060
4609    5061
4610    5062
4611    5064
Name: id, Length: 4612, dtype: int64

In [16]:
police['gender'].value_counts()

M    4398
F     210
Name: gender, dtype: int64

In [17]:
police['gender'].value_counts('F')

M    0.954427
F    0.045573
Name: gender, dtype: float64

In [18]:
police['manner_of_death'].value_counts()

shot                4382
shot and Tasered     230
Name: manner_of_death, dtype: int64

In [36]:
police['armed'].value_counts()

gun                                 2562
knife                                689
unarmed                              294
undetermined                         189
toy weapon                           161
vehicle                               82
unknown weapon                        60
machete                               39
ax                                    23
Taser                                 19
gun and knife                         16
sword                                 16
baseball bat                          13
hammer                                12
metal pipe                            11
box cutter                            10
hatchet                               10
screwdriver                            9
crossbow                               9
gun and car                            7
sharp object                           7
pipe                                   6
piece of wood                          5
blunt object                           5
scissors                               4
metal object                           4
baton                                  4
rock                                   4
gun and vehicle                        4
shovel                                 4
                                    ...
oar                                    1
nail gun                               1
vehicle and gun                        1
walking stick                          1
metal rake                             1
bean-bag gun                           1
cordless drill                         1
pen                                    1
pepper spray                           1
flagpole                               1
air conditioner                        1
samurai sword                          1
hand torch                             1
fireworks                              1
chainsaw                               1
metal hand tool                        1
flashlight                             1
bow and arrow                          1
stapler                                1
contractor's level                     1
tire iron                              1
baseball bat and bottle                1
gun and sword                          1
machete and gun                        1
claimed to be armed                    1
barstool                               1
baseball bat and fireplace poker       1
motorcycle                             1
spear                                  1
bayonet                                1
Name: armed, Length: 84, dtype: int64

In [42]:
by_state = police.groupby('state').agg(len)
by_state

,id,name,date,manner_of_death,armed,age,gender,race,city,signs_of_mental_illness,threat_level,flee,body_camera
state,,,,,,,,,,,,,
AK,32,32,32,32,32,32.0,32,32,32,32,32,32,32
AL,88,88,88,88,88,88.0,88,88,88,88,88,88,88
AR,68,68,68,68,68,68.0,68,68,68,68,68,68,68
AZ,223,223,223,223,223,223.0,223,223,223,223,223,223,223
CA,698,698,698,698,698,698.0,698,698,698,698,698,698,698
CO,159,159,159,159,159,159.0,159,159,159,159,159,159,159
CT,18,18,18,18,18,18.0,18,18,18,18,18,18,18
DC,13,13,13,13,13,13.0,13,13,13,13,13,13,13
DE,11,11,11,11,11,11.0,11,11,11,11,11,11,11
FL,281,281,281,281,281,281.0,281,281,281,281,281,281,281
GA,151,151,151,151,151,151.0,151,151,151,151,151,151,151
HI,26,26,26,26,26,26.0,26,26,26,26,26,26,26
IA,29,29,29,29,29,29.0,29,29,29,29,29,29,29
ID,35,35,35,35,35,35.0,35,35,35,35,35,35,35
IL,95,95,95,95,95,95.0,95,95,95,95,95,95,95
IN,82,82,82,82,82,82.0,82,82,82,82,82,82,82
KS,45,45,45,45,45,45.0,45,45,45,45,45,45,45
KY,80,80,80,80,80,80.0,80,80,80,80,80,80,80
LA,96,96,96,96,96,96.0,96,96,96,96,96,96,96
MA,31,31,31,31,31,31.0,31,31,31,31,31,31,31
MD,67,67,67,67,67,67.0,67,67,67,67,67,67,67
ME,17,17,17,17,17,17.0,17,17,17,17,17,17,17
MI,72,72,72,72,72,72.0,72,72,72,72,72,72,72
MN,57,57,57,57,57,57.0,57,57,57,57,57,57,57
MO,114,114,114,114,114,114.0,114,114,114,114,114,114,114
MS,57,57,57,57,57,57.0,57,57,57,57,57,57,57
MT,24,24,24,24,24,24.0,24,24,24,24,24,24,24
NC,127,127,127,127,127,127.0,127,127,127,127,127,127,127
ND,9,9,9,9,9,9.0,9,9,9,9,9,9,9
NE,20,20,20,20,20,20.0,20,20,20,20,20,20,20
NH,12,12,12,12,12,12.0,12,12,12,12,12,12,12
NJ,59,59,59,59,59,59.0,59,59,59,59,59,59,59
NM,91,91,91,91,91,91.0,91,91,91,91,91,91,91
NV,79,79,79,79,79,79.0,79,79,79,79,79,79,79
NY,80,80,80,80,80,80.0,80,80,80,80,80,80,80
OH,134,134,134,134,134,134.0,134,134,134,134,134,134,134
OK,138,138,138,138,138,138.0,138,138,138,138,138,138,138
OR,72,72,72,72,72,72.0,72,72,72,72,72,72,72
PA,95,95,95,95,95,95.0,95,95,95,95,95,95,95
RI,4,4,4,4,4,4.0,4,4,4,4,4,4,4
SC,72,72,72,72,72,72.0,72,72,72,72,72,72,72
SD,15,15,15,15,15,15.0,15,15,15,15,15,15,15
TN,120,120,120,120,120,120.0,120,120,120,120,120,120,120
TX,410,410,410,410,410,410.0,410,410,410,410,410,410,410
UT,51,51,51,51,51,51.0,51,51,51,51,51,51,51
VA,84,84,84,84,84,84.0,84,84,84,84,84,84,84
VT,8,8,8,8,8,8.0,8,8,8,8,8,8,8
WA,127,127,127,127,127,127.0,127,127,127,127,127,127,127
WI,73,73,73,73,73,73.0,73,73,73,73,73,73,73
WV,50,50,50,50,50,50.0,50,50,50,50,50,50,50
WY,13,13,13,13,13,13.0,13,13,13,13,13,13,13

In [48]:
by_state_arr = police['state'].value_counts()
by_state_arr

CA    698
TX    410
FL    281
AZ    223
CO    159
GA    151
OK    138
OH    134
WA    127
NC    127
TN    120
MO    114
LA     96
IL     95
PA     95
NM     91
AL     88
VA     84
IN     82
NY     80
KY     80
NV     79
WI     73
OR     72
MI     72
SC     72
AR     68
MD     67
NJ     59
MS     57
MN     57
UT     51
WV     50
KS     45
ID     35
AK     32
MA     31
IA     29
HI     26
MT     24
NE     20
CT     18
ME     17
SD     15
DC     13
WY     13
NH     12
DE     11
ND      9
VT      8
RI      4
Name: state, dtype: int64

In [49]:
by_state = pd.DataFrame(by_state_arr)

In [50]:
by_state

    state
CA    698
TX    410
FL    281
AZ    223
CO    159
GA    151
OK    138
OH    134
WA    127
NC    127
TN    120
MO    114
LA     96
IL     95
PA     95
NM     91
AL     88
VA     84
IN     82
NY     80
KY     80
NV     79
WI     73
OR     72
MI     72
SC     72
AR     68
MD     67
NJ     59
MS     57
MN     57
UT     51
WV     50
KS     45
ID     35
AK     32
MA     31
IA     29
HI     26
MT     24
NE     20
CT     18
ME     17
SD     15
DC     13
WY     13
NH     12
DE     11
ND      9
VT      8
RI      4

In [23]:
city_population = pd.read_csv('CityPopulation2000.csv', encoding = "ISO-8859-1")

print(city_population.dtypes) #shows the type of data contained in cells

city_population['Population'] = city_population['Population'].str.replace(r'\(r.*\)', '')#removes anything that has a (r) in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r'\(.*\)', '')#removes anything that has a parenthesis in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r'CDP', '')#removes anything that has a 'CDP' in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r'city', '')#removes anything that has a lowercase spelling of 'city' in it, done to try to clean up data
city_population['City'] = city_population['City'].str.lower()#makes everthing lowercase, done to try to clean up data
type_dict = {'Geographic Area': 'str', 'City': 'str', 'Population': 'int64'}#done to change population values into an integer

city_population = city_population.astype(type_dict)#done to change population values into an integer

print(city_population.dtypes)

city_population

Geographic Area    object
City               object
Population         object
dtype: object
Geographic Area    object
City               object
Population          int64
dtype: object

      Geographic Area                               City  Population
0                  AL                            abanda          192
1                  AL                         abbeville         2688
2                  AL                        adamsville         4522
3                  AL                       addison town         758
4                  AL                         akron town         356
5                  AL                         alabaster        30352
6                  AL                       albertville        21160
7                  AL                    alexander city        14875
8                  AL                        alexandria         3917
9                  AL                        aliceville         2486
10                 AL                       allgood town         622
11                 AL                       altoona town         933
12                 AL                         andalusia         9015
13                 AL                      anderson town         282
14                 AL                          anniston        23106
15                 AL                              arab         8050
16                 AL                       ardmore town        1194
17                 AL                          argo town        4071
18                 AL                        ariton town         764
19                 AL                         arley town         357
20                 AL                       ashford town        2148
21                 AL                       ashland town        2037
22                 AL                          ashville         2212
23                 AL                            athens        21897
24                 AL                            atmore        10194
25                 AL                           attalla         6048
26                 AL                            auburn        53380
27                 AL                  autaugaville town         870
28                 AL                          avon town         543
29                 AL                              axis          757
...               ...                                ...         ...
29493     Puerto Rico               san isidro comunidad        6828
29494     Puerto Rico                 san josé comunidad        2900
29495     Puerto Rico               san juan zona urbana      381931
29496     Puerto Rico            san lorenzo zona urbana        8037
29497     Puerto Rico          san sebastián zona urbana        9622
29498     Puerto Rico            santa bárbara comunidad        4622
29499     Puerto Rico              santa clara comunidad         982
29500     Puerto Rico           santa isabel zona urbana        5976
29501     Puerto Rico            santo domingo comunidad        3156
29502     Puerto Rico                   stella comunidad        1088
29503     Puerto Rico                   suárez comunidad        1931
29504     Puerto Rico                 tallaboa comunidad         925
29505     Puerto Rico            tallaboa alta comunidad        1816
29506     Puerto Rico                    tibes comunidad         362
29507     Puerto Rico                tiburones comunidad        1616
29508     Puerto Rico  tierras nuevas poniente comunidad        3228
29509     Puerto Rico               toa alta zona urbana        3713
29510     Puerto Rico               toa baja zona urbana        1513
29511     Puerto Rico          trujillo alto zona urbana       48437
29512     Puerto Rico                 utuado zona urbana        8397
29513     Puerto Rico                    vayas comunidad         528
29514     Puerto Rico                  vázquez comunidad        1890
29515     Puerto Rico              vega alta zona urbana       10266
29516     Puerto Rico              vega baja zona urbana       25905
29517     Puerto Rico                  vieques comunidad        3316
29518     Puerto Rico                vieques zona urbana        1938
29519     Puerto Rico               villalba zona urbana        3384
29520     Puerto Rico                yabucoa zona urbana        6047
29521     Puerto Rico                  yauco zona urbana       17186
29522     Puerto Rico                   yaurel comunidad        1050

[29523 rows x 3 columns]

In [46]:
by_city_arr = police['city'].value_counts()
by_city_arr

los angeles           71
phoenix               69
houston               47
las vegas             41
san antonio           36
columbus              34
chicago               34
albuquerque           31
miami                 29
st. louis             29
austin                28
jacksonville          26
denver                26
kansas city           26
tucson                25
oklahoma city         25
bakersfield           21
tulsa                 21
atlanta               18
new york              18
louisville            18
fresno                17
dallas                17
mesa                  17
orlando               16
san jose              16
portland              16
indianapolis          16
baltimore             16
arlington             15
                      ..
gardner                1
campbelltown           1
trinity                1
mexico beach           1
brookshire             1
clearlake park         1
bremerton              1
port wentworth         1
crownpoint             1
rosedale               1
mantoloking            1
white lake             1
east ridge             1
pennfield township     1
abington township      1
kirkwood               1
the colony             1
lakemoor               1
leadwood               1
pocatello              1
north hills            1
blountville            1
auburndale             1
kings county           1
lucedale               1
goodbee                1
bastrop                1
lakeshire              1
okmulgee county        1
greenwood              1
Name: city, Length: 2210, dtype: int64

In [45]:
by_city = pd.DataFrame(by_city)
by_city

                    city
los angeles           71
phoenix               69
houston               47
las vegas             41
san antonio           36
columbus              34
chicago               34
albuquerque           31
miami                 29
st. louis             29
austin                28
jacksonville          26
denver                26
kansas city           26
tucson                25
oklahoma city         25
bakersfield           21
tulsa                 21
atlanta               18
new york              18
louisville            18
fresno                17
dallas                17
mesa                  17
orlando               16
san jose              16
portland              16
indianapolis          16
baltimore             16
arlington             15
...                  ...
gardner                1
campbelltown           1
trinity                1
mexico beach           1
brookshire             1
clearlake park         1
bremerton              1
port wentworth         1
crownpoint             1
rosedale               1
mantoloking            1
white lake             1
east ridge             1
pennfield township     1
abington township      1
kirkwood               1
the colony             1
lakemoor               1
leadwood               1
pocatello              1
north hills            1
blountville            1
auburndale             1
kings county           1
lucedale               1
goodbee                1
bastrop                1
lakeshire              1
okmulgee county        1
greenwood              1

[2210 rows x 1 columns]

In [28]:
grouped_tbl = police.groupby("city").agg(len)
selected_tbl = grouped_tbl[["id"]]
selected_tbl = selected_tbl.rename(columns={'id':'kill counts'})
selected_tbl = selected_tbl.rename(columns={'city': 'City'})
selected_tbl

                              kill counts
city
300 block of state line road            1
abbeville                               1
aberdeen                                2
abilene                                 2
abingdon                                2
abington township                       1
acworth                                 1
ada                                     1
adams county                            3
addison                                 1
adelanto                                1
affton                                  1
aguanga                                 1
ahwatukee                               1
aiea                                    1
aiken                                   2
aitkin                                  1
akron                                   6
alamo                                   2
alamogordo                              2
alamosa                                 2
albany                                  2
albert lea                              1
albuquerque                            31
alderwood manor                         1
aldie                                   1
alexandria                              4
algoma township                         1
alhambra                                1
aliceville                              1
...                                   ...
winter haven                            1
winters                                 1
wise county                             1
wolf creek                              1
wolfe county                            1
wood county                             1
wood lake                               1
woodbridge                              2
woodford                                1
woodland                                1
woodlawn                                1
woodstock                               1
woodville                               2
wyoming                                 2
wythe county                            1
wytheville                              1
yakima                                  4
yellville                               1
yonkers                                 2
yorba linda                             1
york                                    5
york county                             2
youngtown                               1
yreka                                   1
yuba city                               2
yucca valley                            1
yulee                                   1
yuma                                    3
zanesville                              1
zion                                    2

[2210 rows x 1 columns]

In [31]:
#test
city_and_state = police[['city', 'state']]
city_and_state

                  city state
0              shelton    WA
1                aloha    OR
2              wichita    KS
3        san francisco    CA
4                evans    CO
5              guthrie    OK
6             chandler    AZ
7              assaria    KS
8           burlington    IA
9            knoxville    PA
10            stockton    CA
11            freeport    TX
12            columbus    OH
13          des moines    IA
14         new orleans    LA
15             huntley    MT
16      salt lake city    UT
17              strong    AR
18            syracuse    UT
19             england    AR
20             el paso    TX
21              arcola    IL
22          south gate    CA
23     north las vegas    NV
24         albuquerque    NM
25          jourdanton    TX
26            st. paul    MN
27     franklin county    MO
28          chesapeake    VA
29          old bridge    NJ
...                ...   ...
4582       elizabethon    TN
4583            sanger    TX
4584           houston    TX
4585          richmond    VA
4586            milton    FL
4587             salem    OR
4588       soddy daisy    TN
4589        long beach    CA
4590       gainesville    GA
4591               ada    OK
4592            austin    TX
4593       los angeles    CA
4594      floyd county    GA
4595            lowell    AR
4596        huntington    WV
4597         richlands    NC
4598           sanford    NC
4599        hartsville    SC
4600           lacombe    LA
4601       hyattsville    MD
4602  lexington county    SC
4603          la habra    CA
4604            dallas    TX
4605      jacksonville    NC
4606         baltimore    MD
4607            boston    MA
4608          longview    TX
4609          monument    CO
4610             miami    FL
4611          new york    NY

[4612 rows x 2 columns]

In [51]:
joined_table = city_and_state.merge('city', by_city, 'city')

ValueError: can not merge DataFrame with instance of type <class 'str'>